package com.mapita.modelo;
// Generated 8/02/2019 09:55:15 PM by Hibernate Tools 4.3.1



/**
 * Marcador generated by hbm2java
 */
public class Marcador  implements java.io.Serializable {


     private int idmarcador;
     private Usuario usuario;
     private String descripcion;
     private Double longitud;
     private Double latitud;

    public Marcador() {
    }

	
    public Marcador(int idmarcador, Usuario usuario) {
        this.idmarcador = idmarcador;
        this.usuario = usuario;
    }
    public Marcador(int idmarcador, Usuario usuario, String descripcion, Double longitud, Double latitud) {
       this.idmarcador = idmarcador;
       this.usuario = usuario;
       this.descripcion = descripcion;
       this.longitud = longitud;
       this.latitud = latitud;
    }
   
    public int getIdmarcador() {
        return this.idmarcador;
    }
    
    public void setIdmarcador(int idmarcador) {
        this.idmarcador = idmarcador;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }
    public Double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }




}


